spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: mongotest
      host: localhost
      port: 27017
      auto-index-creation: true